~name: .NET release build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Program.cs'
      - 'DeadlockEntityHelper.csproj'
      - 'DeadlockEntityHelper.sln'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: |
        dotnet publish -c Release --no-restore --runtime linux-x64
        dotnet publish -c Release --no-restore --runtime win-x64

    - name: Upload the executable
      uses: actions/upload-artifact@v7
      with:
        path:
          - ./bin/Release/net10.0/linux-x64/publish/DeadlockEntityHelper
          - ./bin/Release/net10.0/win-x64/publish/DeadlockEntityHelper.exe
        if-no-files-found: error
        retention-days: 90
        overwrite: true
