name: On Deadlock update

on:
  workflow_dispatch:
    # Inputs

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
    - name: Install SteamCMD, misc deps
      run: |
        mkdir /tmp/steam && pushd /tmp/steam
        curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
        popd
        chmod +x /tmp/steam/steamcmd.sh

    - name: Download latest map
      env:
        STEAM_BOT_USERNAME: ${{ secrets.STEAM_BOT_USERNAME }}
        STEAM_BOT_PASSWORD: ${{ secrets.STEAM_BOT_PASSWORD }}
      run: /tmp/steam/steamcmd.sh \
        +login "$STEAM_BOT_USERNAME" "$STEAM_BOT_PASSWORD" \
        +sDepotDownloadFileFilter "*dl_midtown.vpk" \
        +download_depot 1422450 1422456 _ _ /tmp/deadlock \
        +exit

    # Thanks https://stackoverflow.com/questions/64868918/how-to-download-artifact-release-asset-in-another-workflow
    - name: Get run ID of build workflow
      id: get-run-id
      run: |
        WF_NAME=".NET release build"
        RUN_ID=`gh run --repo ${{ github.repository }} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
        echo "Detected latest run id for workflow ${WF_NAME}: ${RUN_ID}"
        echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"

    - name: Download DeadlockEntityHelper binary
      uses: actions/download-artifact@v8
      with:
        name: DeadlockEntityHelper
        github-token: ${{ github.token }}
        repository: ${{ github.repository }}
        run-id: ${{ steps.get-run-id.outputs.run-id }}

    - run: chmod +x DeadlockEntityHelper
    
    - name: Calculate latest DeadlockEntityHelper outputs
      env:
        MAP_PATH: /tmp/deadlock/game/citadel/maps/dl_midtown.vpk
        CRATE_SUBCLASS: citadel_breakable_prop_wooden_crate
        STATUE_SUBCLASS: citadel_breakable_item_container
      run: |
        DeadlockEntityHelper $MAP_PATH $CRATE_SUBCLASS > crates.json
        DeadlockEntityHelper $MAP_PATH $STATUE_SUBCLASS > golden_statues.json
        CRATE_COUNT=`jq length crates.json`
        STATUE_COUNT=`jq length statues.json`
        cat > output.json << EOF
        {
          "crate_count": $CRATE_COUNT,
          "statue_count": $STATUE_COUNT,
        }
        EOF
        
    - name: Upload the outputs
      uses: actions/upload-artifact@v7
      with:
        path: ./output.json
        if-no-files-found: error
        retention-days: 90
        overwrite: true
        archive: false
